[build]
command = "mkdir -p public && cp index.html public/ && cp *.js public/ && cp *.png public/ && cp _redirects public/"
publish = "public"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

[functions."api"]
timeout = 60

[functions."auto-publisher"]
schedule = "@hourly"
timeout = 60
