[build]
command = "mkdir -p public && cp index.html public/ && cp *.js public/ && cp *.png public/ && cp _redirects public/"
publish = "public"
functions = "netlify/functions"

[functions."api"]
node_bundler = "esbuild"
